services:
  db_mysql:
    container_name: db_mysql
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_test
    ports:
      - "3306:3306"
    volumes:
      # - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

# volumes:
#   db_data: